# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChildLearning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChildLearning
  
  pod 'IQKeyboardManagerSwift'
  pod 'FacebookLogin'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'ChildLearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChildLearningUITests' do
    # Pods for testing
  end

end
